[app]
url_template = "https://{app_name}.capsuleapp.cyou"

[server]
listen_addr = "::"
listen_port = 80

[git_repo]
domain_name = "git.capsuleapp.cyou"
port = 443
base_dir = "/capsule/git"
scheme = "https"