[package]
name = "test-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.4.0", features = ["postgres", "chrono"] }
diesel_migrations = { version = "1.4.0" }

[features]
pg = []