[app]
url_template = "http://{app_name}.capsuleapp.cyou"

[server]
listen_addr = "::"
listen_port = 80

[git_repo]
url_template = "http://git.capsuleapp.cyou:8080/{user_name}/{app_name}.git"
base_dir = "/srv/capsule/git"