[app]
url_template = "https://{app_name}.capsuleapp.cyou"

[server]
listen_addr = "::"
listen_port = 80

[git_repo]
url_template = "https://git.capsuleapp.cyou/{app_name}.git"
base_dir = "/tmp/capsule/git"