[app]
domain_name = "capsuleapp.cyou"
port = 80
scheme = "https"

[server]
listen_addr = "::"
listen_port = 80

[git_repo]
domain_name = "git.capsuleapp.cyou"
port = 80
base_dir = "/capsule/git"
scheme = "http"

