# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-capsule-cli

[print_schema]
file = "src/application/implementation/postgres/schema.rs"
filter = { only_tables = ["capsule_applications"] }